[project]
name = "debugging-q4"
version = "0.1.0"
description = "CCHC Assessment Debugging Q4"
authors = [{ name = "Patrick Farley", email = "pfarley64@gmail.com" }]
readme = "README.md"
requires-python = "<=3.11"
dependencies = [
dash==2.14.2
numpy==2.3.5
pandas==2.3.3
]
